// OHT 스케줄 데이터 (2026)
// 각 예약(job)은: date, customer, info(항공/투어), vehicle(차량+업무), driver(기사), staff(담당)

const DRIVERS = [
  { group: "OHT", name: "加藤 Katou", phone: "080 3232 8884" },
  { group: "OHT", name: "笹森 Sasamori Suguru", phone: "090 7515 8332" },
  { group: "OHT", name: "永田 Michio", phone: "070 9158 2478" },
  { group: "OHT", name: "木村 Kimura", phone: "090 2814 7858" },
  { group: "OHT", name: "渋谷 Shibu", phone: "070 9049 3910" },
  { group: "千章", name: "小山内 愛 Mana", phone: "090 2871 4644" },
  { group: "千章", name: "中島 Nakajima", phone: "080 1899 4661" },
  { group: "千章", name: "高橋 Takahashi", phone: "080 5597 2224" },
  { group: "千章", name: "鳥本 Torimoto", phone: "090 3773 5669" },
  { group: "千章", name: "武川 Takegawa", phone: "090 7052 5106" },
  { group: "千章", name: "大澤 Osawa", phone: "080 5595 0276" },
  { group: "大建", name: "Sawada Masa", phone: "090 9751 6741" },
  { group: "大建", name: "中村 Nakamura", phone: "080 6099 2073" },
  { group: "大建", name: "丸谷 Maruya", phone: "090 6690 1073" },
  { group: "大建", name: "野上 Nogami", phone: "080 4047 4153" },
  { group: "大建", name: "八十島 Yasojima", phone: "080 1896 3158" },
  { group: "大建", name: "本島 Motojima", phone: "080 9321 1042" },
  { group: "大建", name: "波多野 Hatano (shuu san)", phone: "090 5227 0716" },
  { group: "大建", name: "坂本 Sakamoto", phone: "090 9510 8228" },
  { group: "大建", name: "川村 Kawamura", phone: "070 5090 9679" },
  { group: "優駿", name: "ネラ Nera", phone: "070 1613 0216" },
  { group: "優駿", name: "チャガン Chagan", phone: "080 4312 2640" },
  { group: "優駿", name: "坪井 Tsuboi", phone: "080 1896 4095" },
  { group: "優駿", name: "ウィレス Wires", phone: "070 3158 2803" },
  { group: "ひらぎし", name: "Saito", phone: "090 2872 4434" },
  { group: "ひらぎし", name: "Katagiri", phone: "090 9515 9640" },
  { group: "ひらぎし", name: "Tanetani", phone: "090 8879 0122" },
  { group: "ひらぎし", name: "Kugai", phone: "080 6753 4881" },
  { group: "ひらぎし", name: "Kawahara", phone: "080 3262 4342" },
  { group: "ひらぎし", name: "Kishikawa", phone: "090 9753 9385" },
  { group: "森さん", name: "Saito Makoto", phone: "090 2699 2518" },
  { group: "森さん", name: "Mori Kazushi", phone: "090 3114 7367" },
  { group: "森さん", name: "鈴木 Suzuki", phone: "090 5959 5855" },
  { group: "森さん", name: "Sanpei", phone: "090 6269 8280" },
  { group: "森さん", name: "松本 Matsumoto", phone: "070 1216 8130" },
  { group: "森さん", name: "齋藤 Saito", phone: "070 1216 8048" },
  { group: "other", name: "宮崎則明 Miyazaki san", phone: "090 4870 5696" },
  { group: "other", name: "タニワキ Taniwaki san", phone: "090 2695 2017" },
  { group: "other", name: "Wu san", phone: "090 2878 8259" },
  { group: "other", name: "Kou san", phone: "080 5722 9935" },
  { group: "other", name: "JUST つくだ Tsukuda", phone: "080 4048 4441" },
  { group: "other", name: "JUST いまだ Imada", phone: "090 8631 5408" },
  { group: "other", name: "JUST たなか Tanaka", phone: "090 1527 0225" },
  { group: "other", name: "JUST 岩崎 Iwasaki", phone: "090 3398 3268" },
  { group: "other", name: "Recrue ふかつひろし", phone: "090 3397 7831" },
];

// 예약 데이터: month(1-12), day, customer, info, vehicle, driver, staff, tag
// tag: 'tour' | 'off' | 'personal' | 'event'
const JOBS_SEED = [
  // ===== 2026 January =====
  { m:1, d:2, customer:"Simon Barrett", info:"TG670 8:20 - Hakuvilla", vehicle:"Hiace (3) + Alphard (1)", driver:"airport meeting + attendant", staff:"sam" },
  { m:1, d:3, customer:"Mr. Charles Chow 16人", info:"Biei Day Tour 10:30-20:30", vehicle:"Hiace + guide", driver:"中村 080 6099 2073", staff:"youmin" },
  { m:1, d:4, customer:"Rebecca Hunt", info:"CTS (HX690 14:40) - Niseko Kyo", vehicle:"Micro - airport meeting", driver:"Osanae san", staff:"youmin" },
  { m:1, d:5, customer:"Wei Ting Lee 11人", info:"CTS (SQ660 7:30) - Sky Niseko", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"sam" },
  { m:1, d:7, customer:"Ivan Lam", info:"Day Tour", vehicle:"Hiace + guide", driver:"shuu san", staff:"sam" },
  { m:1, d:9, customer:"Bernadette Sahd", info:"5:00 Hakuvilla - CTS (TG671 10:00)", vehicle:"Hiace + attendant + snacks", driver:"", staff:"youmin" },
  { m:1, d:11, customer:"Charles Chow", info:"CTS (CX580 14:50) - Kyo (vale)", vehicle:"Micro + luggage car", driver:"", staff:"Yuka san" },
  { m:1, d:12, customer:"SHEPHARD Cameron 11人", info:"CTS (JL509 11:25) - MaxValu - Vale Niseko", vehicle:"Micro - airport meeting", driver:"", staff:"Yuka san" },
  { m:1, d:13, customer:"JOHNSTON Elizabeth 9人", info:"13:00 CTS - OMO7 Asahikawa", vehicle:"Large Bus - airport meeting", driver:"", staff:"Yuka san" },
  { m:1, d:16, customer:"Luca Giovannetti", info:"CTS (JL501 9:00) - Vale Niseko", vehicle:"Micro - airport meeting", driver:"", staff:"Yuka san" },
  { m:1, d:17, customer:"Wendy Smith + booster seats", info:"CTS (CX580 15:50) - Niseko Kyo", vehicle:"Micro - airport meeting", driver:"6244 Tanaka 09015270225", staff:"Peta (maybe)" },
  { m:1, d:18, customer:"MONO (Charles Chow group)", info:"Hakuvilla - TG671", vehicle:"Large Bus + attendant + snacks", driver:"", staff:"youmin" },
  { m:1, d:19, customer:"COLLETT Jordan", info:"CX580 14:50 - Chalet Ivy", vehicle:"Micro - airport meeting", driver:"", staff:"Mori san" },
  { m:1, d:23, customer:"Dave Tran", info:"CTS (NH57 11:05) - Miru Niseko", vehicle:"Micro - airport meeting", driver:"加藤 899", staff:"sam" },
  { m:1, d:24, customer:"Jessica Ogden-Barry 7人", info:"CTS (QF107 18:00) - Fenix Furano", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"youmin" },
  { m:1, d:25, customer:"Japan Ski Tours (CME)", info:"10:00 CTS - Shimukappu - Furano La Vista", vehicle:"Large Bus - airport meeting", driver:"5013 Tanaka 09015270225", staff:"sam" },
  { m:1, d:27, customer:"Wei Xiang Lim 10人", info:"CTS (SQ660 7:30) - Vale Rusutsu", vehicle:"Micro - airport meeting", driver:"木村 899", staff:"youmin" },
  { m:1, d:29, customer:"Wei Xiang Lim 10人", info:"Toya Day Tour", vehicle:"Micro + guide", driver:"木村", staff:"youmin" },
  { m:1, d:30, customer:"Krystle Lim", info:"NH65 14:35 - Club Med Tomamu", vehicle:"Large bus - airport meeting", driver:"6086 市原 090 6692 4916", staff:"sam" },
  { m:1, d:31, customer:"Saada Malouf 10人", info:"CTS (CX580 14:50) - Vale Rusutsu", vehicle:"Micro - airport meeting", driver:"mana chan", staff:"sam" },

  // ===== 2026 February =====
  { m:2, d:1, customer:"Japan Ski Tours (CME)", info:"10:00 CTS - Shimukappu - Furano La Vista", vehicle:"Large Bus - airport meeting", driver:"5437 Murai 08034748640", staff:"sam" },
  { m:2, d:1, customer:"VLADISLAV CHUPOV 12人", info:"CTS (JL519 16:00) - The Vale Niseko", vehicle:"Micro + luggage Hiace", driver:"加藤", staff:"sam" },
  { m:2, d:4, customer:"Japan Ski Tours (HI10)", info:"13:00 CTS - OMO7 Asahikawa", vehicle:"Large Bus - airport meeting", driver:"881 マルコ", staff:"peta" },
  { m:2, d:4, customer:"Sachi Oda 14人", info:"CTS (JL511 12:00) - Escon - Sapporo Hotel", vehicle:"Micro + guide", driver:"木村 901", staff:"youmin" },
  { m:2, d:5, customer:"Debbie Whittaker 8人", info:"CTS (GK103 8:55) - Niseko Kyo", vehicle:"Micro - airport meeting", driver:"torimoto", staff:"sam" },
  { m:2, d:6, customer:"Canal Direto", info:"CTS - Shikotsu - Sapporo", vehicle:"Mid-size Bus - airport meeting", driver:"533 iwasaki", staff:"sam" },
  { m:2, d:6, customer:"Sachi Oda 14人", info:"Otaru Day Tour", vehicle:"2 Hiace + guide", driver:"笹森 & 澤田", staff:"youmin" },
  { m:2, d:8, customer:"Al-thani Hamad", info:"JL507 10:35 - Niseko Kyo", vehicle:"Gold Micro + luggage", driver:"958 ochan", staff:"sam" },
  { m:2, d:9, customer:"Carlos Larriba", info:"CX584 15:55 - M Hotel Niseko", vehicle:"Micro - airport meeting", driver:"大畑 899", staff:"youmin" },
  { m:2, d:14, customer:"Mr. Charles Chow 44人", info:"CTS (NH53 9:40) - Hakuvilla", vehicle:"2台 Large Bus - snacks", driver:"JUST", staff:"youmin" },
  { m:2, d:14, customer:"LIU Qinjie 12人", info:"CTS (CX580 14:50) - Vale Niseko + Skye", vehicle:"Micro - airport meeting", driver:"osanai san 582", staff:"sam" },
  { m:2, d:15, customer:"Mr. Charles Chow 44人", info:"2台 Large Bus + Alphard - airport meeting", vehicle:"", driver:"6244 imada", staff:"youmin" },
  { m:2, d:15, customer:"Andy Schachtel", info:"5J5128 17:25 - Vale Niseko", vehicle:"Micro", driver:"木村 899", staff:"youmin" },
  { m:2, d:17, customer:"Eric Melbihess", info:"CTS (NH4721 12:45) - The Vale Niseko", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"youmin" },
  { m:2, d:17, customer:"HAENGGI Jamie", info:"GK119 AA9052 19:45 - Always Niseko", vehicle:"Micro", driver:"木村 899", staff:"youmin" },
  { m:2, d:18, customer:"Japan Ski Tours (HI10)", info:"13:00 CTS - OMO7 Asahikawa", vehicle:"Large Bus - airport meeting", driver:"6244 tanaka", staff:"sam" },
  { m:2, d:18, customer:"Heli (Breuer)", info:"CTS (NH65 14:35) - Aspect Niseko", vehicle:"Micro", driver:"大畑 958", staff:"sam" },
  { m:2, d:19, customer:"Chherry Phat", info:"CTS TG670 8:30 - Silver Dream Chalet", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"sam" },
  { m:2, d:21, customer:"Regina Lau", info:"CTS JL507 10:35 - Toya Nonokaze", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"sam" },
  { m:2, d:21, customer:"Mr. Charles Chow 44人", info:"15:00 Hakuvilla - CTS (NH082 20:30)", vehicle:"2台 Large Bus - snacks", driver:"JUST", staff:"youmin" },
  { m:2, d:21, customer:"ROBERTSON Nick 13人", info:"CTS (QF107 17:55) - Snow Crystal", vehicle:"Micro - super long", driver:"加藤 901", staff:"sam" },
  { m:2, d:22, customer:"Mr. Charles Chow", info:"15:00 Hakuvilla - CTS (NH082 20:30)", vehicle:"2台 Large Bus + attend", driver:"tanaka & imada", staff:"youmin" },
  { m:2, d:24, customer:"Tyler Noel 2人", info:"10:00 Niseko - Otaru", vehicle:"otaru one day", driver:"shuu san", staff:"youmin" },
  { m:2, d:28, customer:"Gidanart Yu", info:"TG670 8:20 - Mitsui - 15:00 Tomamu", vehicle:"Large bus 1068 + guide", driver:"タカハシ", staff:"sam" },
  { m:2, d:6, customer:"Jennifer Hicks", info:"Multiday Tour (2/6-2/12)", vehicle:"Vellfire", driver:"Shibu", staff:"" },

  // ===== 2026 March =====
  { m:3, d:1, customer:"Ian Yao 10人 + child seats", info:"CTS (JAL503 9:00) - Setsu Niseko", vehicle:"Micro - airport meeting", driver:"mana chan 582", staff:"youmin" },
  { m:3, d:2, customer:"Tracey Nicholls 9人", info:"CTS (QF107 18:00) - Maples", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"youmin" },
  { m:3, d:5, customer:"Andrew Turner 2人", info:"Toya one day", vehicle:"Vellfire + guide", driver:"Suguru", staff:"youmin" },
  { m:3, d:5, customer:"TIMOTHY Jan 7人", info:"CTS (XJ620 10:40) - Vale Niseko", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"sam" },
  { m:3, d:7, customer:"LI Helen 28人", info:"CTS (HX692 15:15) - The Vale Niseko", vehicle:"Large bus - airport meeting", driver:"1100 meguro", staff:"sam" },
  { m:3, d:10, customer:"Swee Si Min 9人", info:"CTS (NH73 18:35) - Mercure Sapporo", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"youmin" },
  { m:3, d:13, customer:"Woon Pin Beh (Alvin) 9人", info:"CTS (JL2501 11:25) - Vale Rusutsu", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"sam" },
  { m:3, d:13, customer:"James Ong", info:"CTS 15:00 - Asahikawa Hotel", vehicle:"Large Bus - airport meeting", driver:"7700 hunaki", staff:"youmin" },
  { m:3, d:14, customer:"Raycher Lim 14人", info:"CTS (MU279 12:30) - Keio Prelia Sapporo", vehicle:"Micro - airport meeting", driver:"木村 899", staff:"youmin" },
  { m:3, d:15, customer:"Han Feng Lim 12人", info:"CTS (BR116 14:05) - The Vale Rusutsu", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"sam" },
  { m:3, d:16, customer:"WEI Leonard 11人", info:"CTS (CX580 14:50) - Niseko Kyo", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"youmin" },
  { m:3, d:16, customer:"Melissa Mutolo", info:"CTS (NH73 18:35) - Airbnb", vehicle:"Hiace/Alphard - airport meeting", driver:"toursbylocals", staff:"cancelled" },
  { m:3, d:17, customer:"Ms Victoria 12人", info:"CTS KE765 12:50 - Tomamu The Tower", vehicle:"Micro - airport meeting", driver:"加藤 901", staff:"sam" },
  { m:3, d:19, customer:"25/26 X5+ Seasonpass Workshop", info:"Sapporo Day Tour", vehicle:"Large - airport meeting", driver:"200 Satou", staff:"youmin" },
  { m:3, d:20, customer:"Ms. Alvina 3人", info:"Sapporo Day Tour", vehicle:"Vellfire + guide", driver:"永田", staff:"youmin" },
  { m:3, d:21, customer:"Mr. Leonardo Ginting 17人", info:"CTS (TG 670 8:20) - AYA Niseko", vehicle:"Micro + guide", driver:"木村 901", staff:"youmin" },
  { m:3, d:21, customer:"Venon Tian 9人", info:"CTS (5J5128 17:25) - Maples Niseko", vehicle:"Micro - airport meeting", driver:"坪井 898", staff:"sam" },
  { m:3, d:22, customer:"Mark Tan 15人", info:"", vehicle:"", driver:"", staff:"" },
  { m:3, d:25, customer:"Fiona Bartholomeusz", info:"CTS (JL511 11:55) - MUWA Niseko", vehicle:"Hiace + airport meeting", driver:"takahashi san", staff:"sam" },
  { m:3, d:27, customer:"Elizabeth Dee 17人", info:"CTS (KE765 12:50) - The Maples Niseko", vehicle:"Large Bus - airport meeting", driver:"5653", staff:"sam" },
  { m:3, d:26, customer:"お疲れパーティー", info:"team dinner party", vehicle:"", driver:"", staff:"", tag:"event" },
  { m:3, d:27, customer:"10:30 team meeting", info:"", vehicle:"", driver:"", staff:"", tag:"event" },

  // ===== 2026 April =====
  { m:4, d:1, customer:"Danford Sy 16人", info:"9:00-18:00 Sapporo Toursbylocals", vehicle:"Micro + guide", driver:"笹森 901", staff:"sam" },
  { m:4, d:4, customer:"Dream Creations 10人", info:"CTS (TR892 17:55) - Sapporo Stream Hotel", vehicle:"Micro + guide", driver:"901 kato san", staff:"sam" },
  { m:4, d:5, customer:"Dream Creations", info:"Otaru Day Tour", vehicle:"Micro + guide", driver:"958", staff:"sam" },
  { m:4, d:6, customer:"Dream Creations", info:"Sapporo Day Tour", vehicle:"Micro + guide", driver:"958", staff:"sam" },
  { m:4, d:6, customer:"Vince Montealto", info:"Biei/Furano Tour 11:30-21:30", vehicle:"Micro + guide", driver:"笹森 901", staff:"" },
  { m:4, d:7, customer:"Dream Creations", info:"Biei/Furano Day Tour", vehicle:"Micro + guide", driver:"958", staff:"sam" },
  { m:4, d:15, customer:"Shrikant Ghanshaym Shah", info:"CTS - Sapporo Day Tour", vehicle:"Micro + guide", driver:"cancelled", staff:"sam" },
  { m:4, d:16, customer:"Shrikant Ghanshaym Shah", info:"Otaru Day Tour", vehicle:"Micro + guide", driver:"cancelled", staff:"sam" },
  { m:4, d:19, customer:"Vas Family", info:"9:00-17:30 Sapporo Tour", vehicle:"Hiace + guide", driver:"shibu", staff:"youmin" },
  { m:4, d:30, customer:"Ms. Meliana", info:"Sapporo Day Tour", vehicle:"Hiace + guide", driver:"michio", staff:"youmin" },

  // ===== 2026 May =====
  { m:5, d:1, customer:"Ms. Meliana", info:"Otaru Day Tour", vehicle:"Hiace + guide", driver:"michio", staff:"youmin" },
  { m:5, d:2, customer:"Ms. Meliana", info:"Asahikawa Day Tour", vehicle:"Hiace + guide", driver:"michio", staff:"youmin" },
  { m:5, d:3, customer:"Ms. Meliana", info:"Furano Day Tour", vehicle:"Hiace + guide", driver:"michio", staff:"youmin" },
  { m:5, d:4, customer:"Ms. Meliana", info:"Sapporo Day Tour", vehicle:"Hiace + guide", driver:"michio", staff:"youmin" },
  { m:5, d:8, customer:"Fay Wang 4人", info:"Otaru Tour 8:30-14:00", vehicle:"Hiace + guide", driver:"shibu", staff:"youmin" },
  { m:5, d:19, customer:"Mr. Von Finck Luitpold", info:"Sapporo tour 9:00-13:00", vehicle:"guide", driver:"osanai", staff:"youmin" },
  { m:5, d:30, customer:"Pierre-Henri & Isabelle", info:"CTS (NH63 13:35)", vehicle:"airport meeting", driver:"sam", staff:"peta" },

  // ===== 2026 June =====
  { m:6, d:12, customer:"nanporo work day", info:"everyone", vehicle:"", driver:"", staff:"", tag:"event" },
  { m:6, d:12, customer:"Monica Yap 4人", info:"CTS (NH53 9:35) - Tokachi", vehicle:"Hiace - airport meeting", driver:"shibu", staff:"sam" },
  { m:6, d:13, customer:"Selene Tan 11人", info:"CTS (TG670 8:20)", vehicle:"Micro - airport meeting", driver:"suguru san 958 + vellfire", staff:"sam" },
  { m:6, d:19, customer:"Jeremy Oh 15名", info:"CTS (TG670 8:20) - Toya", vehicle:"Micro - airport meeting", driver:"Kimura 901", staff:"youmin" },
  { m:6, d:19, customer:"Jeremy Oh 15名", info:"もみじ台 ホクノースーパー", vehicle:"ガイド送迎", driver:"", staff:"youmin" },
  { m:6, d:21, customer:"Jeremy Oh 15名", info:"荷物", vehicle:"", driver:"", staff:"youmin" },
  { m:6, d:22, customer:"Andy Chen", info:"Furano/Biei Day Tour", vehicle:"Alphard + guide", driver:"yasojima san", staff:"sam" },
  { m:6, d:4, customer:"susukino meeting 19:00", info:"everyone", vehicle:"", driver:"", staff:"", tag:"event" },

  // ===== 2026 July (current month) =====
  { m:7, d:5, customer:"Jeni Nishimura", info:"JL515 14:15", vehicle:"airport meeting", driver:"", staff:"sam" },
  { m:7, d:6, customer:"W Travel 10人", info:"Kushiro", vehicle:"micro + guide", driver:"", staff:"sam" },
  { m:7, d:7, customer:"W Travel", info:"Lake Akan", vehicle:"micro + guide", driver:"", staff:"sam" },
  { m:7, d:8, customer:"W Travel", info:"Lake Akan", vehicle:"micro + guide", driver:"", staff:"sam" },
  { m:7, d:9, customer:"W Travel", info:"Shiretoko", vehicle:"micro + guide", driver:"", staff:"sam" },
  { m:7, d:9, customer:"Yum and group", info:"CTS (WE531 13:45)", vehicle:"Hiace - collect ¥700,000", driver:"shibu", staff:"youmin" },
  { m:7, d:10, customer:"W Travel", info:"Shiretoko", vehicle:"micro + guide", driver:"", staff:"sam" },
  { m:7, d:10, customer:"Yum and group (5 pax)", info:"", vehicle:"gold micro + guide", driver:"kimura san", staff:"youmin" },
  { m:7, d:11, customer:"W Travel", info:"Abashiri", vehicle:"micro + guide", driver:"", staff:"sam" },
  { m:7, d:11, customer:"Yum and group (5 pax)", info:"", vehicle:"micro + guide", driver:"kimura san", staff:"youmin" },
  { m:7, d:12, customer:"W Travel", info:"Memanbetsu Airport", vehicle:"micro + guide", driver:"", staff:"sam" },
  { m:7, d:12, customer:"Yum and group (5 pax)", info:"", vehicle:"micro + guide", driver:"kimura san", staff:"youmin" },
  { m:7, d:13, customer:"Yum and group (5 pax)", info:"", vehicle:"micro + guide", driver:"kimura san", staff:"youmin" },
  { m:7, d:14, customer:"Yum and group (5 pax)", info:"", vehicle:"micro + guide", driver:"kimura san", staff:"youmin" },
  { m:7, d:15, customer:"Yum and group (5 pax)", info:"", vehicle:"micro + guide", driver:"kimura san", staff:"youmin" },
  { m:7, d:16, customer:"Gnext Summit", info:"Multiday Tour", vehicle:"Micro + guide", driver:"", staff:"sam" },
  { m:7, d:16, customer:"Yum and group (5 pax)", info:"", vehicle:"micro + guide", driver:"kimura san", staff:"youmin" },
  { m:7, d:17, customer:"Gnext Summit", info:"Multiday Tour", vehicle:"Micro + guide", driver:"", staff:"sam" },
  { m:7, d:17, customer:"Yum and group (5 pax)", info:"", vehicle:"micro + guide", driver:"kimura san", staff:"youmin" },
  { m:7, d:17, customer:"김현기", info:"CTS-Hilton Niseko Village", vehicle:"Micro + airport meet", driver:"shibu / 大畑", staff:"" },
  { m:7, d:18, customer:"Gnext Summit", info:"Multiday Tour", vehicle:"Micro + guide", driver:"", staff:"sam" },
  { m:7, d:18, customer:"Yum and group (5 pax)", info:"", vehicle:"micro + guide", driver:"kimura san", staff:"youmin" },
  { m:7, d:19, customer:"Gnext Summit", info:"Multiday Tour", vehicle:"Micro + guide", driver:"", staff:"sam" },
  { m:7, d:19, customer:"Yum and group", info:"stay toya", vehicle:"", driver:"", staff:"youmin" },
  { m:7, d:20, customer:"Yum and group", info:"help kimura san", vehicle:"", driver:"", staff:"youmin" },
  { m:7, d:22, customer:"Yum and group", info:"help kimura san", vehicle:"", driver:"", staff:"youmin" },
  { m:7, d:27, customer:"한국방송학회 9人", info:"", vehicle:"micro + airport meeting", driver:"", staff:"youmin" },
  { m:7, d:28, customer:"한국방송학회 9人", info:"", vehicle:"Alphard + guide", driver:"", staff:"youmin" },
  { m:7, d:29, customer:"한국방송학회 9人", info:"", vehicle:"Alphard + guide", driver:"", staff:"youmin" },
  { m:7, d:31, customer:"Nina Garcia", info:"Furano Day Tour", vehicle:"Alphard + guide", driver:"shibu", staff:"sam" },

  // ===== 2026 August =====
  { m:8, d:8, customer:"VIAGGI NEL MONDO SRL", info:"Otaru/Shakotan Day Tour, collect ¥148,500", vehicle:"7:50 at PINN-N4E2-II", driver:"", staff:"sam" },
];

// 직원 휴무/부재 (staff off days). person: 'sam'|'youmin'|'peta'|'shibu' 등
const STAFF_OFF_SEED = [
  // 2026 April
  { m:4, d:8, person:"sam", note:"韓国 (4/8-4/16)" },
  { m:4, d:9, person:"sam", note:"韓国" },
  { m:4, d:10, person:"sam", note:"韓国" },
  { m:4, d:11, person:"sam", note:"韓国" },
  { m:4, d:12, person:"sam", note:"韓国" },
  { m:4, d:13, person:"sam", note:"韓国" },
  { m:4, d:14, person:"sam", note:"韓国" },
  { m:4, d:15, person:"sam", note:"韓国" },
  { m:4, d:16, person:"sam", note:"韓国" },
  { m:4, d:25, person:"youmin", note:"california (4/25-4/30)" },
  { m:4, d:26, person:"youmin", note:"california" },
  { m:4, d:27, person:"youmin", note:"california" },
  { m:4, d:28, person:"youmin", note:"california" },
  { m:4, d:29, person:"youmin", note:"california" },
  { m:4, d:30, person:"youmin", note:"california" },
  // 2026 May
  { m:5, d:5, person:"youmin", note:"休み" },
  { m:5, d:6, person:"youmin", note:"休み" },
  { m:5, d:7, person:"youmin", note:"休み" },
  { m:5, d:2, person:"youmin", note:"california (5/2-5/16)" },
  { m:5, d:3, person:"youmin", note:"california" },
  { m:5, d:4, person:"youmin", note:"california" },
  // 2026 June
  { m:6, d:8, person:"sam", note:"afternoon remote" },
  // 2026 July
  { m:7, d:12, person:"youmin", note:"休み" },
  { m:7, d:13, person:"sam", note:"休み" },
];

const MONTH_NAMES = ["", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
// 각 월 1일의 요일 (2026년). 0=Sun ... 6=Sat
const FIRST_WEEKDAY_2026 = { 1:4, 2:0, 3:0, 4:3, 5:5, 6:1, 7:3, 8:6, 9:2, 10:4, 11:0, 12:2 };
const DAYS_IN_MONTH_2026 = { 1:31, 2:28, 3:31, 4:30, 5:31, 6:30, 7:31, 8:31, 9:30, 10:31, 11:30, 12:31 };

// 담당자별 색상
const STAFF_COLORS = {
  sam: "#c0392b",
  youmin: "#1f6f8b",
  peta: "#8e44ad",
  shibu: "#d68910",
  michio: "#16a085",
};
